version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /$PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: host
    depends_on:
      - prometheus

volumes:
  grafana-storage:
    external: true
